### PR TITLE
IFCB dataset integration

### PR DESCRIPTION
**Pull request by pglez82**
Code needed for loading the IFCB dataset into QuaPy.

### CODE REVIEW

**Comment by AlexMoreo** [comment]
Merged! thanks for the contribution. A possible improvement would be to add a parameter "val_split", or "val_samples", or something similar, which is 0 by default (which corresponds to the current behavior), but that returns, for values v>0, a val_generator that yields v held-out training samples for validation purposes. To be coherent with the current specifications of the dataset, it seems reasonable that these v samples are the last ones from the training ones. Would that make sense?

**Comment by pglez82** [comment]
Yes, it would make sense. What I am not totally sure about is the strategy of taking the last samples from the training set for validation. Maybe a better strategy is to do this randomly. This is a time series so discarding all samples contiguously can be problematic.

Appart from the previous discussion, what I really think would be positive,  would be to have a "default" split so in order to compare quantification methods. That way, everyone can have the same train/val split, and the comparison would be fair. 

A proposal would be to add a parameter val_split that if true, the method will return some samples for training and others for validation (always the same ones). If false, what we have now. What do you think?

**Comment by AlexMoreo** [comment]
I agree that a "default" split should be provided so that everyone can refer to IFCB in the same terms. In this case, I would suggest that the fetch_IFCB function receives one optional argument "for_model_selection" (default: False) to keep coherence with the interface of fetch_twitter. This would make the syntax of the returned object consistent. The effect of setting True or False would simply result in the objects being returned to be interpreted as a training and validation datasets (False), or as a training+validation and test (True), just like with Tweets datasets.

What I am not pretty sure about returning samples that correspond to different samples merged together. I know nothing about plankton species, but I could guess there is some internal information within a true water sample that could be lost when merging different samples. E.g., if the presence of certain species A precludes the presence of another species B in a water sample, then this information will be irretrievably lost in the training set, but still present in the test samples.

**Comment by pglez82** [comment]
I want to finish this PR. Sorry for leaving it unattended for so long.

> # I agree that a "default" split should be provided so that everyone can refer to IFCB in the same terms. In this case, I would suggest that the fetch_IFCB function receives one optional argument "for_model_selection" (default: False) to keep coherence with the interface of fetch_twitter. This would make the syntax of the returned object consistent. The effect of setting True or False would simply result in the objects being returned to be interpreted as a training and validation datasets (False), or as a training+validation and test (True), just like with Tweets datasets.

Ok, I will try to make the implementation coherent with the twitter dataset.

> # What I am not pretty sure is about returning samples that correspond to different samples merged together. I know nothing about plankton species, but I could guess there is some internal information within a true water sample that could be lost when merging different samples. E.g., if the presence of certain species A precludes the presence of another species B in a water sample, then this information will be irretrievably lost in the training set, but still present in the test samples.

do you mean, delete the flag "single_sample_train=True" and return always a generator of samples? I like the option of returning everything together just in case the user wants to train a simple quantifier in a straightforward manner.  You always have the option of setting the flag as false and return the samples individually.

**Comment by AlexMoreo** [comment]
Merged into master, v0.1.8. Thanks!

**Comment by AlexMoreo** [comment]
Closed

**Pull request closed without merging**
