### PR TITLE
uci multiclass datasets

### PR DESCRIPTION
**Pull request by pglez82**
Code for integrating 5 multiclass datasets from UCI using their python package. This will add one dependency. Install with:

```
pip install ucimlrepo
```

Usage example:
```python
import quapy as qp
from sklearn.linear_model import LogisticRegression

for dataset in qp.datasets.UCI_MULTICLASS_DATASETS:
    dataset = qp.datasets.fetch_UCIMulticlassDataset(dataset)
    model = qp.method.aggregative.ACC(LogisticRegression())
    model.fit(dataset.training)
    estim_prevalence = model.quantify(dataset.test.instances)
    true_prevalence  = dataset.test.prevalence()
    error = qp.error.mae(true_prevalence, estim_prevalence)
    print(f'Mean Absolute Error (MAE)={error:.3f}')
```

### CODE REVIEW

**Review by AlexMoreo — CHANGES_REQUESTED** [review]
Can you please update the documentation? right now, it says something like "Loads ...  as used in `Pérez-Gállego, P., Quevedo, J. R., & del Coz, J. J. (2017)." which seems to be a "copy-paste" from the UCI *binary* dataset fetch documentation.

**Review by AlexMoreo — CHANGES_REQUESTED** [review]
Can you please use the qp.utils.pickled_resource instead of 1) checking whether the pickle exists, and 2) creating it otherwise?

**Review by AlexMoreo — CHANGES_REQUESTED** [review]
the verbose variable seems to have no effect; could you add and if before data.stats()?

**Comment by pglez82** [comment]
I think I have solved all the issues. Let me know if anything arises.

**Pull request merged**
